version: '3'
services:
  zk1:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zk2:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zk3:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  dubbo-admin:
    image: dubbo-admin:2.5.4
    container_name: dubbo-admin
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - "7001:8080"
    environment:
      ZOO_SERVERS: zk1:2181?backup=zk2:2181,zk3:2181
    networks:
      - my-net

  dubbo-monitor:
    container_name: dubbo-monitor
    image: duboo-monitor:1.0
    volumes:
        - ./dubbo.properties:/opt/conf/dubbo.properties
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
    - "9001:9001"
    - "7070:7070"
    logging:
      driver: json-file
      options:
        max-size: 100m
    networks:
    - my-net

  zkui:
     container_name: zkui
     image: zkui
     depends_on:
       - zk1
       - zk2
       - zk3
     ports:
       - "9090:9090"
     environment:
         ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
     networks:
       - my-net

networks:
  my-net:
    driver: bridge
