version: "2"
services:
  kafka:
    image: kafka:1.1.0
    container_name: kafka
    restart: always
    environment:
      JMX_PORT: 1099
      BROKER_ID: 0
      ZOO_SERVERS: zk1:2181,zk2:2181,zk3:2181
    expose:
      - 9092
    depends_on:
      - zk3
      - zk2
      - zk1
    networks:
      - my-net

  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.3.0
    container_name: kafka-rest
    restart: always
    environment:
    - KAFKA_REST_ZOOKEEPER_CONNECT=zk1:2181/kafka
    - KAFKA_REST_LISTENERS=http://kafka-rest:8082
    - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:9092
    - KAFKA_REST_HOST_NAME=kafka-rest
    expose:
      - 8082
    depends_on:
      - zk3
      - zk2
      - zk1
    logging:
      driver: json-file
      options:
        max-size: 100m
    networks:
      - my-net

  kafka-topics-ui:
    image: kafka-topic-ui:1.0
    container_name: kafka-topics-ui
    ports:
      - 19000:8000
    depends_on:
      - kafka
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true
    networks:
          - my-net

  zk1:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zk2:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zk3:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zkui:
     container_name: zkui
     image: zkui
     ports:
       - "9090:9090"
     depends_on:
       - zk1
       - zk2
       - zk3
     environment:
         ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
     networks:
       - my-net

networks:
  my-net:
    driver: bridge