version: '2'
services:
  kafka:
    image: kafka:1.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
      KAFKA_LOG_RETENTION_HOURS: 12
      KAFKA_HEAP_OPTS: "-Xmx256m"
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      - my-net

  zk1:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zk2:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net

  zk3:
    image: zookeeper:3.4.12
    restart: always
    container_name: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - my-net


  zkui:
     container_name: zkui
     image: zkui
     ports:
       - "9090:9090"
     environment:
         ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
     networks:
       - my-net

networks:
  my-net:
    driver: bridge